### ISSUE TITLE
TorchIO has been supporting Python 3.12 since 0.19.6

### ISSUE THREAD

**Issue by aywi** [conda-forge/torchio-feedstock#73]
### Comment:

TorchIO has been supporting Python 3.12 since 0.19.6:
https://github.com/fepegar/torchio/blob/13407ab7f6d562a0953fa6642ce198f297129589/setup.cfg#L53
Details can be found at fepegar/torchio#1114

The Python version requirement should be updated to `<3.13` since Python 3.12 has become the default version on many platforms:
https://github.com/conda-forge/torchio-feedstock/blob/fa631419ee8e19af25ef23390e0c3845cc8c4193/recipe/meta.yaml#L21-L36

**Comment by sarthakpati** [comment]
Good point - thank you!

Would you mind putting a PR so that this gets recorded as your contribution?

**Comment by aywi** [comment]
> Good point - thank you!
> 
> Would you mind putting a PR so that this gets recorded as your contribution?

Thanks! I have created a PR, please review it later.
